/* Instructions ************

Implement test for the following test method :
- getAccountById_givenAccountId_returnsAccount
- getAccountById_givenOpportunityId_throwsException

Goal: Drive the stub behavior to returns and throws
Note: Reuse the same principles used in step 1
Tips: Look at the [returns](https://github.com/salesforce/apex-mockery/blob/main/force-app/recipes/classes/mocking/Returns.cls)
      and [throws](https://github.com/salesforce/apex-mockery/blob/main/force-app/recipes/classes/mocking/Throws.cls) samples.
*/
@IsTest
private class AccountServiceTestExercise2 {
  @isTest
  static void getAccountById_givenAccountId_returnsAccount() {
    // Arrange
    

    // Act
    

    // Assert

  }

  @isTest
  static void getAccountById_givenOpportunityId_throwsException() {
    // Arrange
    

    // Act
    

    // Assert

  }
}
